version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: mysql_larvel_container
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: usmandb
      MYSQL_USER: usman
      MYSQL_PASSWORD: usman1
    networks:
      my_custom_network:
        ipv4_address: 172.18.0.2  # Custom IP address for MySQL
    ports:
      - "3309:3306"
    volumes:
      - db-data:/var/lib/mysql

  laravel-app:
    build:
      context: ./laravel
      dockerfile: Dockerfile
    ports:
      - "81:80"
    networks:
      my_custom_network:
        ipv4_address: 172.18.0.3  # Custom IP address for Laravel
    depends_on:
      - mysql
    command:
      - sh
      - -c
      - |
        sleep 30 &&
        /usr/local/bin/php /phpdocker/temp12/artisan migrate &&
        /usr/local/bin/apache2-foreground

volumes:
  db-data:

networks:
  my_custom_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16  # Custom subnet for the network
